### ISSUE TITLE
More pixels on your OLEDs

### ISSUE THREAD

**Issue by janlindblom** [Jonathan357611/Calc-V1#1]
Hi Jonathan! It looks from your photos like the displays are 128x64 pixel OLEDs, if you update the code here you’ll get more pixels and more lines 😊

https://github.com/Jonathan357611/Calc-V1/blob/db8b68eb85d8cfbc807bc955f78a8b0b3b610925/code.py#L31

**Comment by jonatfm** [comment]
Yes, your right, This is kind of a 'hacky' trick. These are 128x64, but the font was too small, so I practically double it in height by doing this.

But thank you for actually taking the time and reading through my code <3

**Comment by janlindblom** [comment]
Alright I understand, good hack then! 😊

**Comment by jonatfm** [comment]
Thanks!
